#!/bin/sh

set -e

case "$1" in
    configure)
    gtk-update-icon-cache -f -t /usr/share/icons/Windows10
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
